[2022-08-08 16:46:56 ()] | [30]: discord.client > PyNaCl is not installed, voice will NOT be supported
[2022-08-08 16:46:56 ()] | [20]: discord.client > logging in using static token
[2022-08-08 16:46:56 ()] | [20]: ext.dev.evaluator > ext.dev.evaluator initialized
[2022-08-08 16:46:56 ()] | [20]: discord.gateway > Shard ID None has sent the IDENTIFY payload.
[2022-08-08 16:46:56 ()] | [20]: discord.gateway > Shard ID None has connected to Gateway (Session ID: e8ab446256c733c09741cd694b612320).
[2022-08-08 17:17:08 ()] | [30]: discord.client > PyNaCl is not installed, voice will NOT be supported
[2022-08-08 17:17:08 ()] | [20]: discord.client > logging in using static token
[2022-08-08 17:17:08 ()] | [20]: ext.dev.evaluator > ext.dev.evaluator initialized
[2022-08-08 17:17:09 ()] | [20]: discord.gateway > Shard ID None has sent the IDENTIFY payload.
[2022-08-08 17:17:09 ()] | [20]: discord.gateway > Shard ID None has connected to Gateway (Session ID: cd59f225b4c250b9b1a01416fc4cd036).
[2022-08-08 17:18:27 ()] | [30]: discord.client > PyNaCl is not installed, voice will NOT be supported
[2022-08-08 17:18:27 ()] | [20]: discord.client > logging in using static token
[2022-08-08 17:18:28 ()] | [20]: ext.dev.evaluator > ext.dev.evaluator initialized
[2022-08-08 17:18:28 ()] | [20]: discord.gateway > Shard ID None has sent the IDENTIFY payload.
[2022-08-08 17:18:28 ()] | [20]: discord.gateway > Shard ID None has connected to Gateway (Session ID: d3615bcd5bf680023b3f60f1dd7632bb).
[2022-08-08 17:20:44 ()] | [30]: discord.client > PyNaCl is not installed, voice will NOT be supported
[2022-08-08 17:20:44 ()] | [20]: discord.client > logging in using static token
[2022-08-08 17:20:44 ()] | [20]: ext.dev.evaluator > ext.dev.evaluator initialized
[2022-08-08 17:20:45 ()] | [20]: discord.gateway > Shard ID None has sent the IDENTIFY payload.
[2022-08-08 17:20:45 ()] | [20]: discord.gateway > Shard ID None has connected to Gateway (Session ID: dbd1cbbd9b1a6b182b38d3c4f9add6b4).
[2022-08-08 17:21:01 ()] | [10]: ext.role_buttons > checking select interaction
[2022-08-08 17:21:43 ()] | [10]: ext.role_buttons > checking select interaction
[2022-08-08 17:25:19 ()] | [10]: ext.role_buttons > checking select interaction
[2022-08-08 17:25:19 ()] | [40]: discord.ui.view > Ignoring exception in view <RoleSelectorView timeout=600 children=1> for item <Select placeholder='Roles selected will be added to the self assigner' min_values=0 max_values=7 options=[<SelectOption label='@everyone' value=970761243277266944 description=None emoji=None default=False>, <SelectOption label='\u200b' value=970761968665374731 description=None emoji=None default=False>, <SelectOption label='director' value=970763686224474222 description=None emoji=None default=False>, <SelectOption label='member' value=971105474437058571 description=None emoji=None default=False>, <SelectOption label='dev' value=973668885196849212 description=None emoji=None default=False>, <SelectOption label='booster' value=983480102329385061 description=None emoji=None default=False>, <SelectOption label='stealth bot' value=1003372159302901840 description=None emoji=None default=False>] disabled=False>
Traceback (most recent call last):
  File "/home/arc/club/pyhnix-beta/.venv/lib/python3.8/site-packages/discord/ui/view.py", line 423, in _scheduled_task
    await item.callback(interaction)
TypeError: callback() missing 1 required positional argument: 's_interaction'
[2022-08-08 17:28:40 ()] | [10]: ext.role_buttons > checking select interaction
[2022-08-08 17:28:40 ()] | [40]: discord.ui.view > Ignoring exception in view <RoleSelectorView timeout=600 children=1> for item <Select placeholder='Roles selected will be added to the self assigner' min_values=0 max_values=7 options=[<SelectOption label='@everyone' value=970761243277266944 description=None emoji=None default=False>, <SelectOption label='\u200b' value=970761968665374731 description=None emoji=None default=False>, <SelectOption label='director' value=970763686224474222 description=None emoji=None default=False>, <SelectOption label='member' value=971105474437058571 description=None emoji=None default=False>, <SelectOption label='dev' value=973668885196849212 description=None emoji=None default=False>, <SelectOption label='booster' value=983480102329385061 description=None emoji=None default=False>, <SelectOption label='stealth bot' value=1003372159302901840 description=None emoji=None default=False>] disabled=False>
Traceback (most recent call last):
  File "/home/arc/club/pyhnix-beta/.venv/lib/python3.8/site-packages/discord/ui/view.py", line 423, in _scheduled_task
    await item.callback(interaction)
  File "/home/arc/club/pyhnix-beta/ext/role_buttons.py", line 255, in callback
    logger.debug("selected changes: %s", selector_view.values)
AttributeError: 'RoleSelectorView' object has no attribute 'values'
[2022-08-08 17:31:47 ()] | [10]: ext.role_buttons > checking select interaction
[2022-08-08 17:31:47 ()] | [40]: discord.ui.view > Ignoring exception in view <RoleSelectorView timeout=600 children=1> for item <Select placeholder='Roles selected will be added to the self assigner' min_values=0 max_values=7 options=[<SelectOption label='@everyone' value=970761243277266944 description=None emoji=None default=False>, <SelectOption label='\u200b' value=970761968665374731 description=None emoji=None default=False>, <SelectOption label='director' value=970763686224474222 description=None emoji=None default=False>, <SelectOption label='member' value=971105474437058571 description=None emoji=None default=False>, <SelectOption label='dev' value=973668885196849212 description=None emoji=None default=False>, <SelectOption label='booster' value=983480102329385061 description=None emoji=None default=False>, <SelectOption label='stealth bot' value=1003372159302901840 description=None emoji=None default=False>] disabled=False>
Traceback (most recent call last):
  File "/home/arc/club/pyhnix-beta/.venv/lib/python3.8/site-packages/discord/ui/view.py", line 423, in _scheduled_task
    await item.callback(interaction)
  File "/home/arc/club/pyhnix-beta/ext/role_buttons.py", line 255, in callback
    logger.debug("selected changes: %s", selector_view.values)
AttributeError: 'RoleSelectorView' object has no attribute 'values'
[2022-08-08 17:32:24 ()] | [10]: ext.role_buttons > checking select interaction
[2022-08-08 17:32:24 ()] | [10]: ext.role_buttons > selected changes
[2022-08-08 17:32:24 ()] | [10]: ext.role_buttons > adding button for role: director (970763686224474222)
[2022-08-08 17:32:24 ()] | [10]: ext.role_buttons > adding button for role: member (971105474437058571)
[2022-08-08 17:32:24 ()] | [10]: ext.role_buttons > adding button for role: dev (973668885196849212)
[2022-08-08 17:32:24 ()] | [10]: ext.role_buttons > adding button for role: booster (983480102329385061)
[2022-08-08 17:32:31 ()] | [10]: ext.role_buttons > role button pressed: director (970763686224474222)
[2022-08-08 17:32:31 ()] | [10]: ext.role_buttons > removing role: director (970763686224474222)
[2022-08-08 17:32:38 ()] | [10]: ext.role_buttons > role button pressed: director (970763686224474222)
[2022-08-08 17:32:38 ()] | [10]: ext.role_buttons > adding role: director (970763686224474222)
[2022-08-08 17:32:41 ()] | [10]: ext.role_buttons > role button pressed: member (971105474437058571)
[2022-08-08 17:32:41 ()] | [10]: ext.role_buttons > removing role: member (971105474437058571)
[2022-08-08 17:32:46 ()] | [10]: ext.role_buttons > role button pressed: member (971105474437058571)
[2022-08-08 17:32:46 ()] | [10]: ext.role_buttons > adding role: member (971105474437058571)
[2022-08-08 20:46:33 ()] | [20]: discord.client > Got a request to RESUME the websocket.
[2022-08-08 20:46:33 ()] | [20]: discord.gateway > Shard ID None has sent the RESUME payload.
[2022-08-08 20:46:33 ()] | [20]: discord.gateway > Shard ID None has successfully RESUMED session dbd1cbbd9b1a6b182b38d3c4f9add6b4.
[2022-08-08 22:27:17 ()] | [20]: discord.gateway > Websocket closed with WSCloseCode.ABNORMAL_CLOSURE, attempting a reconnect.
[2022-08-08 22:27:17 ()] | [20]: discord.client > Got a request to RESUME the websocket.
[2022-08-08 22:27:17 ()] | [20]: discord.gateway > Shard ID None has sent the RESUME payload.
[2022-08-08 22:27:17 ()] | [20]: discord.gateway > Shard ID None session has been invalidated.
[2022-08-08 22:27:17 ()] | [20]: discord.client > Got a request to IDENTIFY the websocket.
[2022-08-08 22:27:22 ()] | [20]: discord.gateway > Shard ID None has sent the IDENTIFY payload.
[2022-08-08 22:27:23 ()] | [20]: discord.gateway > Shard ID None has connected to Gateway (Session ID: abc893b5723822f767c5b4dce690b9de).
[2022-08-09 09:00:18 ()] | [20]: discord.gateway > Timed out receiving packet. Attempting a reconnect.
[2022-08-09 09:00:18 ()] | [20]: discord.client > Got a request to RESUME the websocket.
[2022-08-09 09:00:28 ()] | [40]: discord.client > Attempting a reconnect in 1.82s
Traceback (most recent call last):
  File "/home/arc/club/pyhnix-beta/.venv/lib/python3.8/site-packages/aiohttp/connector.py", line 1154, in _create_direct_connection
    hosts = await asyncio.shield(host_resolved)
  File "/home/arc/club/pyhnix-beta/.venv/lib/python3.8/site-packages/aiohttp/connector.py", line 880, in _resolve_host
    addrs = await self._resolver.resolve(host, port, family=self._family)
  File "/home/arc/club/pyhnix-beta/.venv/lib/python3.8/site-packages/aiohttp/resolver.py", line 33, in resolve
    infos = await self._loop.getaddrinfo(
  File "/home/arc/.pyenv/versions/3.8.11/lib/python3.8/asyncio/base_events.py", line 825, in getaddrinfo
    return await self.run_in_executor(
  File "/home/arc/.pyenv/versions/3.8.11/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/arc/.pyenv/versions/3.8.11/lib/python3.8/socket.py", line 918, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -3] Temporary failure in name resolution

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/arc/club/pyhnix-beta/.venv/lib/python3.8/site-packages/discord/client.py", line 677, in connect
    self.ws = await asyncio.wait_for(coro, timeout=60.0)
  File "/home/arc/.pyenv/versions/3.8.11/lib/python3.8/asyncio/tasks.py", line 494, in wait_for
    return fut.result()
  File "/home/arc/club/pyhnix-beta/.venv/lib/python3.8/site-packages/discord/gateway.py", line 358, in from_client
    gateway = gateway or await client.http.get_gateway()
  File "/home/arc/club/pyhnix-beta/.venv/lib/python3.8/site-packages/discord/http.py", line 2354, in get_gateway
    data = await self.request(Route('GET', '/gateway'))
  File "/home/arc/club/pyhnix-beta/.venv/lib/python3.8/site-packages/discord/http.py", line 617, in request
    async with self.__session.request(method, url, **kwargs) as response:
  File "/home/arc/club/pyhnix-beta/.venv/lib/python3.8/site-packages/aiohttp/client.py", line 1138, in __aenter__
    self._resp = await self._coro
  File "/home/arc/club/pyhnix-beta/.venv/lib/python3.8/site-packages/aiohttp/client.py", line 535, in _request
    conn = await self._connector.connect(
  File "/home/arc/club/pyhnix-beta/.venv/lib/python3.8/site-packages/aiohttp/connector.py", line 542, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "/home/arc/club/pyhnix-beta/.venv/lib/python3.8/site-packages/aiohttp/connector.py", line 907, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "/home/arc/club/pyhnix-beta/.venv/lib/python3.8/site-packages/aiohttp/connector.py", line 1166, in _create_direct_connection
    raise ClientConnectorError(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host discord.com:443 ssl:default [Temporary failure in name resolution]
[2022-08-09 09:00:40 ()] | [40]: discord.client > Attempting a reconnect in 3.69s
Traceback (most recent call last):
  File "/home/arc/club/pyhnix-beta/.venv/lib/python3.8/site-packages/aiohttp/connector.py", line 1154, in _create_direct_connection
    hosts = await asyncio.shield(host_resolved)
  File "/home/arc/club/pyhnix-beta/.venv/lib/python3.8/site-packages/aiohttp/connector.py", line 880, in _resolve_host
    addrs = await self._resolver.resolve(host, port, family=self._family)
  File "/home/arc/club/pyhnix-beta/.venv/lib/python3.8/site-packages/aiohttp/resolver.py", line 33, in resolve
    infos = await self._loop.getaddrinfo(
  File "/home/arc/.pyenv/versions/3.8.11/lib/python3.8/asyncio/base_events.py", line 825, in getaddrinfo
    return await self.run_in_executor(
  File "/home/arc/.pyenv/versions/3.8.11/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/arc/.pyenv/versions/3.8.11/lib/python3.8/socket.py", line 918, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -3] Temporary failure in name resolution

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/arc/club/pyhnix-beta/.venv/lib/python3.8/site-packages/discord/client.py", line 677, in connect
    self.ws = await asyncio.wait_for(coro, timeout=60.0)
  File "/home/arc/.pyenv/versions/3.8.11/lib/python3.8/asyncio/tasks.py", line 494, in wait_for
    return fut.result()
  File "/home/arc/club/pyhnix-beta/.venv/lib/python3.8/site-packages/discord/gateway.py", line 358, in from_client
    gateway = gateway or await client.http.get_gateway()
  File "/home/arc/club/pyhnix-beta/.venv/lib/python3.8/site-packages/discord/http.py", line 2354, in get_gateway
    data = await self.request(Route('GET', '/gateway'))
  File "/home/arc/club/pyhnix-beta/.venv/lib/python3.8/site-packages/discord/http.py", line 617, in request
    async with self.__session.request(method, url, **kwargs) as response:
  File "/home/arc/club/pyhnix-beta/.venv/lib/python3.8/site-packages/aiohttp/client.py", line 1138, in __aenter__
    self._resp = await self._coro
  File "/home/arc/club/pyhnix-beta/.venv/lib/python3.8/site-packages/aiohttp/client.py", line 535, in _request
    conn = await self._connector.connect(
  File "/home/arc/club/pyhnix-beta/.venv/lib/python3.8/site-packages/aiohttp/connector.py", line 542, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "/home/arc/club/pyhnix-beta/.venv/lib/python3.8/site-packages/aiohttp/connector.py", line 907, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "/home/arc/club/pyhnix-beta/.venv/lib/python3.8/site-packages/aiohttp/connector.py", line 1166, in _create_direct_connection
    raise ClientConnectorError(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host discord.com:443 ssl:default [Temporary failure in name resolution]
[2022-08-09 09:00:45 ()] | [20]: discord.gateway > Shard ID None has sent the RESUME payload.
[2022-08-09 09:00:45 ()] | [20]: discord.gateway > Shard ID None session has been invalidated.
[2022-08-09 09:00:45 ()] | [20]: discord.client > Got a request to IDENTIFY the websocket.
[2022-08-09 09:00:50 ()] | [20]: discord.gateway > Shard ID None has sent the IDENTIFY payload.
[2022-08-09 09:00:51 ()] | [20]: discord.gateway > Shard ID None has connected to Gateway (Session ID: ff95cb2ff8f9ea62ebdb08a91084e976).
[2022-08-09 09:22:17 ()] | [30]: discord.client > PyNaCl is not installed, voice will NOT be supported
[2022-08-09 09:22:17 ()] | [20]: discord.client > logging in using static token
[2022-08-09 09:22:17 ()] | [20]: ext.dev.evaluator > ext.dev.evaluator initialized
[2022-08-09 09:22:17 ()] | [20]: discord.gateway > Shard ID None has sent the IDENTIFY payload.
[2022-08-09 09:22:17 ()] | [20]: discord.gateway > Shard ID None has connected to Gateway (Session ID: 0ad07617a66fa4e07d36eb56886e3871).
[2022-08-09 09:22:48 ()] | [10]: ext.role_buttons > checking select interaction
[2022-08-09 09:22:48 ()] | [10]: ext.role_buttons > selected changes
[2022-08-09 09:22:48 ()] | [10]: ext.role_buttons > adding button for role: director (970763686224474222)
[2022-08-09 09:22:48 ()] | [10]: ext.role_buttons > adding button for role: booster (983480102329385061)
[2022-08-09 09:22:48 ()] | [10]: ext.role_buttons > adding button for role: member (971105474437058571)
[2022-08-09 09:22:48 ()] | [10]: ext.role_buttons > adding button for role: dev (973668885196849212)
[2022-08-09 09:23:02 ()] | [10]: ext.role_buttons > role button pressed: dev (973668885196849212)
[2022-08-09 09:23:02 ()] | [10]: ext.role_buttons > removing role: dev (973668885196849212)
[2022-08-09 09:23:09 ()] | [10]: ext.role_buttons > role button pressed: dev (973668885196849212)
[2022-08-09 09:23:09 ()] | [10]: ext.role_buttons > adding role: dev (973668885196849212)
[2022-08-09 09:23:18 ()] | [10]: ext.role_buttons > checking select interaction
[2022-08-09 09:23:18 ()] | [10]: ext.role_buttons > selected changes
[2022-08-09 09:23:18 ()] | [10]: ext.role_buttons > adding button for role: director (970763686224474222)
[2022-08-09 09:23:18 ()] | [10]: ext.role_buttons > adding button for role: booster (983480102329385061)
[2022-08-09 09:23:18 ()] | [10]: ext.role_buttons > adding button for role: member (971105474437058571)
[2022-08-09 09:23:18 ()] | [10]: ext.role_buttons > adding button for role: dev (973668885196849212)
[2022-08-09 09:23:18 ()] | [10]: ext.role_buttons > adding button for role: @everyone (970761243277266944)
[2022-08-09 09:23:30 ()] | [10]: ext.role_buttons > role button pressed: @everyone (970761243277266944)
[2022-08-09 09:23:30 ()] | [10]: ext.role_buttons > removing role: @everyone (970761243277266944)
[2022-08-09 09:23:30 ()] | [40]: discord.ui.view > Ignoring exception in view <RoleButtonView timeout=180.0 children=9> for item <RoleButton style=<ButtonStyle.primary: 1> url=None disabled=False label='@everyone' emoji=None row=None>
Traceback (most recent call last):
  File "/home/arc/club/pyhnix-beta/.venv/lib/python3.8/site-packages/discord/ui/view.py", line 423, in _scheduled_task
    await item.callback(interaction)
  File "/home/arc/club/pyhnix-beta/ext/role_buttons.py", line 52, in callback
    await interaction.user.remove_roles(self.role, reason="role assigner")
  File "/home/arc/club/pyhnix-beta/.venv/lib/python3.8/site-packages/discord/member.py", line 1059, in remove_roles
    await req(guild_id, user_id, role.id, reason=reason)
  File "/home/arc/club/pyhnix-beta/.venv/lib/python3.8/site-packages/discord/http.py", line 733, in request
    raise NotFound(response, data)
discord.errors.NotFound: 404 Not Found (error code: 10011): Unknown Role
[2022-08-09 09:23:44 ()] | [10]: ext.role_buttons > checking select interaction
[2022-08-09 09:23:44 ()] | [10]: ext.role_buttons > selected changes
[2022-08-09 09:23:44 ()] | [10]: ext.role_buttons > adding button for role: director (970763686224474222)
[2022-08-09 09:23:47 ()] | [10]: ext.role_buttons > role button pressed: director (970763686224474222)
[2022-08-09 09:23:47 ()] | [10]: ext.role_buttons > removing role: director (970763686224474222)
[2022-08-09 09:23:49 ()] | [10]: ext.role_buttons > role button pressed: director (970763686224474222)
[2022-08-09 09:23:49 ()] | [10]: ext.role_buttons > adding role: director (970763686224474222)
[2022-08-09 09:23:53 ()] | [10]: ext.role_buttons > role button pressed: director (970763686224474222)
[2022-08-09 09:23:53 ()] | [10]: ext.role_buttons > removing role: director (970763686224474222)
[2022-08-09 09:23:54 ()] | [10]: ext.role_buttons > role button pressed: director (970763686224474222)
[2022-08-09 09:23:54 ()] | [10]: ext.role_buttons > adding role: director (970763686224474222)
[2022-08-09 09:25:55 ()] | [10]: ext.role_buttons > checking select interaction
[2022-08-09 09:25:55 ()] | [10]: ext.role_buttons > selected changes
[2022-08-09 09:25:55 ()] | [10]: ext.role_buttons > adding button for role: dev (973668885196849212)
[2022-08-09 09:25:55 ()] | [10]: ext.role_buttons > adding button for role: member (971105474437058571)
[2022-08-09 09:25:59 ()] | [10]: ext.role_buttons > checking select interaction
[2022-08-09 09:25:59 ()] | [10]: ext.role_buttons > selected changes
[2022-08-09 09:25:59 ()] | [10]: ext.role_buttons > 973668885196849212 is already a button
[2022-08-09 09:25:59 ()] | [10]: ext.role_buttons > 971105474437058571 is already a button
[2022-08-09 09:25:59 ()] | [10]: ext.role_buttons > adding button for role: stealth bot (1003372159302901840)
[2022-08-09 09:26:08 ()] | [10]: ext.role_buttons > checking select interaction
[2022-08-09 09:26:08 ()] | [10]: ext.role_buttons > selected changes
[2022-08-09 09:26:08 ()] | [10]: ext.role_buttons > 971105474437058571 is already a button
[2022-08-09 09:26:12 ()] | [10]: ext.role_buttons > checking select interaction
[2022-08-09 09:26:12 ()] | [10]: ext.role_buttons > selected changes
[2022-08-09 09:28:38 ()] | [10]: ext.role_buttons > checking select interaction
[2022-08-09 09:28:38 ()] | [10]: ext.role_buttons > selected changes
[2022-08-09 09:28:38 ()] | [10]: ext.role_buttons > adding button for role: director (970763686224474222)
[2022-08-09 09:28:50 ()] | [10]: ext.role_buttons > checking select interaction
[2022-08-09 09:28:50 ()] | [10]: ext.role_buttons > selected changes
[2022-08-09 09:28:50 ()] | [10]: ext.role_buttons > 970763686224474222 is already a button
[2022-08-09 09:28:50 ()] | [10]: ext.role_buttons > adding button for role: ​ (970761968665374731)
[2022-08-09 09:28:53 ()] | [10]: ext.role_buttons > role button pressed: ​ (970761968665374731)
[2022-08-09 09:28:53 ()] | [10]: ext.role_buttons > removing role: ​ (970761968665374731)
[2022-08-09 09:28:56 ()] | [10]: ext.role_buttons > role button pressed: ​ (970761968665374731)
[2022-08-09 09:28:56 ()] | [10]: ext.role_buttons > adding role: ​ (970761968665374731)
[2022-08-09 09:29:10 ()] | [10]: ext.role_buttons > checking select interaction
[2022-08-09 09:29:10 ()] | [10]: ext.role_buttons > selected changes
[2022-08-09 09:39:35 ()] | [10]: ext.role_buttons > checking select interaction
[2022-08-09 09:39:35 ()] | [10]: ext.role_buttons > selected changes
[2022-08-09 09:39:35 ()] | [10]: ext.role_buttons > adding button for role: director (970763686224474222)
[2022-08-09 09:39:35 ()] | [10]: ext.role_buttons > adding button for role: booster (983480102329385061)
[2022-08-09 09:39:45 ()] | [10]: ext.role_buttons > checking select interaction
[2022-08-09 09:39:45 ()] | [10]: ext.role_buttons > selected changes
[2022-08-09 09:39:45 ()] | [10]: ext.role_buttons > adding button for role: director (970763686224474222)
[2022-08-09 09:39:45 ()] | [10]: ext.role_buttons > adding button for role: booster (983480102329385061)
[2022-08-09 09:39:45 ()] | [10]: ext.role_buttons > adding button for role: stealth bot (1003372159302901840)
[2022-08-09 09:39:49 ()] | [10]: ext.role_buttons > checking select interaction
[2022-08-09 09:39:49 ()] | [10]: ext.role_buttons > selected changes
[2022-08-09 09:39:49 ()] | [10]: ext.role_buttons > adding button for role: director (970763686224474222)
[2022-08-09 09:39:49 ()] | [10]: ext.role_buttons > adding button for role: booster (983480102329385061)
[2022-08-09 09:39:49 ()] | [10]: ext.role_buttons > adding button for role: stealth bot (1003372159302901840)
[2022-08-09 09:39:49 ()] | [10]: ext.role_buttons > adding button for role: member (971105474437058571)
[2022-08-09 09:39:49 ()] | [10]: ext.role_buttons > adding button for role: dev (973668885196849212)
[2022-08-09 09:40:05 ()] | [10]: ext.role_buttons > checking select interaction
[2022-08-09 09:40:05 ()] | [10]: ext.role_buttons > selected changes
[2022-08-09 09:42:26 ()] | [10]: ext.role_buttons > checking select interaction
[2022-08-09 09:42:26 ()] | [10]: ext.role_buttons > selected changes
[2022-08-09 09:42:26 ()] | [10]: ext.role_buttons > adding button for role: test role (1006557979585290240)
[2022-08-09 09:42:26 ()] | [10]: ext.role_buttons > adding button for role: stealth bot (1003372159302901840)
[2022-08-09 09:42:26 ()] | [10]: ext.role_buttons > adding button for role: dev (973668885196849212)
[2022-08-09 09:42:50 ()] | [10]: ext.role_buttons > checking select interaction
[2022-08-09 09:42:50 ()] | [10]: ext.role_buttons > selected changes
[2022-08-09 09:42:50 ()] | [10]: ext.role_buttons > adding button for role: test role (1006557979585290240)
[2022-08-09 09:42:50 ()] | [10]: ext.role_buttons > adding button for role: dev (973668885196849212)
[2022-08-09 09:42:54 ()] | [10]: ext.role_buttons > checking select interaction
[2022-08-09 09:42:54 ()] | [10]: ext.role_buttons > selected changes
[2022-08-09 09:42:54 ()] | [10]: ext.role_buttons > adding button for role: dev (973668885196849212)
[2022-08-09 09:42:57 ()] | [10]: ext.role_buttons > checking select interaction
[2022-08-09 09:42:57 ()] | [10]: ext.role_buttons > selected changes
[2022-08-09 09:42:57 ()] | [10]: ext.role_buttons > adding button for role: dev (973668885196849212)
[2022-08-09 09:42:57 ()] | [10]: ext.role_buttons > adding button for role: test role (1006557979585290240)
[2022-08-09 09:43:07 ()] | [10]: ext.role_buttons > role button pressed: test role (1006557979585290240)
[2022-08-09 09:43:07 ()] | [10]: ext.role_buttons > adding role: test role (1006557979585290240)
[2022-08-09 09:43:07 ()] | [40]: discord.ui.view > Ignoring exception in view <RoleButtonView timeout=180.0 children=2> for item <RoleButton style=<ButtonStyle.primary: 1> url=None disabled=False label='test role' emoji=None row=None>
Traceback (most recent call last):
  File "/home/arc/club/pyhnix-beta/.venv/lib/python3.8/site-packages/discord/ui/view.py", line 423, in _scheduled_task
    await item.callback(interaction)
  File "/home/arc/club/pyhnix-beta/ext/role_buttons.py", line 60, in callback
    await interaction.user.add_roles(self.role, reason="role assigner")
  File "/home/arc/club/pyhnix-beta/.venv/lib/python3.8/site-packages/discord/member.py", line 1014, in add_roles
    await req(guild_id, user_id, role.id, reason=reason)
  File "/home/arc/club/pyhnix-beta/.venv/lib/python3.8/site-packages/discord/http.py", line 733, in request
    raise NotFound(response, data)
discord.errors.NotFound: 404 Not Found (error code: 10011): Unknown Role
[2022-08-09 10:51:57 ()] | [20]: discord.gateway > Websocket closed with WSCloseCode.ABNORMAL_CLOSURE, attempting a reconnect.
[2022-08-09 10:51:57 ()] | [20]: discord.client > Got a request to RESUME the websocket.
[2022-08-09 10:51:57 ()] | [20]: discord.gateway > Shard ID None has sent the RESUME payload.
[2022-08-09 10:51:58 ()] | [20]: discord.gateway > Shard ID None has successfully RESUMED session 0ad07617a66fa4e07d36eb56886e3871.
[2022-08-09 12:17:41 ()] | [20]: discord.client > Got a request to RESUME the websocket.
[2022-08-09 12:17:41 ()] | [20]: discord.gateway > Shard ID None has sent the RESUME payload.
[2022-08-09 12:17:41 ()] | [20]: discord.gateway > Shard ID None has successfully RESUMED session 0ad07617a66fa4e07d36eb56886e3871.
[2022-08-09 13:07:54 ()] | [20]: discord.client > Got a request to RESUME the websocket.
[2022-08-09 13:07:54 ()] | [20]: discord.gateway > Shard ID None has sent the RESUME payload.
[2022-08-09 13:07:54 ()] | [20]: discord.gateway > Shard ID None has successfully RESUMED session 0ad07617a66fa4e07d36eb56886e3871.
[2022-08-09 14:02:18 ()] | [20]: discord.gateway > Websocket closed with WSCloseCode.ABNORMAL_CLOSURE, attempting a reconnect.
[2022-08-09 14:02:18 ()] | [20]: discord.client > Got a request to RESUME the websocket.
[2022-08-09 14:02:18 ()] | [20]: discord.gateway > Shard ID None has sent the RESUME payload.
[2022-08-09 14:02:19 ()] | [20]: discord.gateway > Shard ID None has successfully RESUMED session 0ad07617a66fa4e07d36eb56886e3871.
[2022-08-09 15:43:09 ()] | [20]: discord.gateway > Websocket closed with WSCloseCode.ABNORMAL_CLOSURE, attempting a reconnect.
[2022-08-09 15:43:09 ()] | [20]: discord.client > Got a request to RESUME the websocket.
[2022-08-09 15:43:09 ()] | [20]: discord.gateway > Shard ID None has sent the RESUME payload.
[2022-08-09 15:43:09 ()] | [20]: discord.gateway > Shard ID None has successfully RESUMED session 0ad07617a66fa4e07d36eb56886e3871.
